version: 2.1

orbs:
    deploygate: horie1024/deploygate@0.0.1

jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Execute assembleDebug
          command: ./gradlew assembleDebug
      - deploygate/distribute:
          token: DEPLOY_GATE_TOKEN
          user_name: DEPLOY_GATE_USER
          apk_path: app/build/outputs/apk/debug/app-debug.apk
          message: Hello World!